spring:
  datasource:
   #  url: jdbc:mysql://localhost:3306/test
     url: jdbc:mysql://10.101.25.142:3306/metabase
     username: root
   #  password: 123
     password: 078c50
     driver-class-name: com.mysql.jdbc.Driver
